### PR TITLE
Update python-eccodes version to >=0.9.8

### PR DESCRIPTION
**Pull request by iainrussell**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This addresses #25 by setting the version of python-eccodes from the date-based 2020.06 to the equivalent 'proper' version, 0.9.8 (even though that version is not available on conda, hopefully the next available one, 1.4.0, will be fine).

### CODE REVIEW

**Comment by iainrussell** [comment]
@conda-forge-admin, please rerender

**Comment by iainrussell** [comment]
I believe this is ready now - without this fix, cfgrib is uninstallable from conda!

**Comment by alexamici** [comment]
@iainrussell I added you to the Maintainers list, you should be able to merge the PR yourself shortly.

**Comment by iainrussell** [comment]
Thank you @alexamici ! I think you need to modify meta.yml  - the readme is generated from that. And you might have to do it as a PR before the servers will pick it up (not sure about that last point though).

**Comment by alexamici** [comment]
I'll merge the PR in the meanwhile

**Comment by iainrussell** [comment]
Thanks Alessandro!

**Pull request merged**
